#!/usr/bin/env escript
% vi: filetype=erlang
%% -*- erlang -*-
%%! -smp enable -pa ebin


main(_Args) ->
    code:add_path("ebin"),
    application:start(sasl),
    application:start(ensy),
    lists:map(fun(App) -> io:format("~p~n", [App]) end, 
        application:which_applications()),
    io:get_chars("> ", 0).
